version: '3'
services: 
  app:
    build: .
    tty: true # コンテナを永続化
    volumes:
      - ./:/go/src/api-salto-theme
    depends_on:
      - db
    ports:
      - "8080:8080"
  
  db:
    image: mysql:5.7
    ports:
      - "3306"
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql

      