version: 2.1

jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run:
          name: これ以降CI/CDが行える
          command: ls -la
      - run:
          name: コンテナプロセス
          command: docker-compose ps
      - run:
          name: goのビルド
          command: docker exec repo_app_1 go build cmd/main.go cmd/db_connector.go
      - run:
          name: ビルドしたファイルをデプロイ
          command: sh shell/deploy.sh
      
      - run:
          name: docker-compose down
          command: docker-compose down

workflows:
  sample: 
    jobs:
      - build
